### ISSUE TITLE
10 depth layers

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/EA-Atlantis-dev#2]
@jessmt 

R code:

```R
library(rbgm)
bgm <- bgmfile(bgmfiles::bgmfiles("antarctica_28"))
boxes <- boxSpatial(bgm)

depths <- sort(abs(c(-2000, -1000, -750, -400, -300,  -200, -100, -50, -20, 0)))

findInterval(abs(boxes$botz), depths)
# [1] 10  7  7  7  7  7  7 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
as.integer(boxes$boundary)
# [1] 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
```

**Comment by jessmt** [comment]
@mdsumner here are the old files

[hydro-forcing-11-layers.zip](https://github.com/AustralianAntarcticDivision/EA-Atlantis-dev/files/2753963/hydro-forcing-11-layers.zip)

**Comment by mdsumner** [comment]
Thanks!  Got it running now, should be done some time tonight

**Comment by mdsumner** [comment]
New files. I still think the scaling is wrong for transport, but we can figure that out if the thing runs. 


[hydro_antarctica_28_2019-01-14.zip](https://github.com/AustralianAntarcticDivision/EA-Atlantis-dev/files/2754708/hydro_antarctica_28_2019-01-14.zip)


Generated with this version of the script: https://github.com/AustralianAntarcticDivision/angstroms/blob/e3fbcd335c2670462cf24d83222cf1571b2fe5e2/inst/couple-Atlantis/coupling-Dec_2018/coupling_versionDece2018.R
